// Scenario presets that modify simulation parameters

export const SCENARIOS = {
  normal: {
    label: 'Normal',
    icon: '🚦',
    description: 'Balanced daily traffic',
    spawnRate: 2.0,
    globalCap: 20,
    weather: 'clear',
    accident: false,
  },
  rush: {
    label: 'Rush Hour',
    icon: '🚗',
    description: 'Peak congestion, 3x spawn rate',
    spawnRate: 0.7,
    globalCap: 34,
    weather: 'clear',
    accident: false,
  },
  night: {
    label: 'Night',
    icon: '🌙',
    description: 'Low traffic, headlights on',
    spawnRate: 4.5,
    globalCap: 10,
    weather: 'clear',
    accident: false,
  },
  rain: {
    label: 'Rain',
    icon: '🌧️',
    description: 'Wet roads, slower traffic',
    spawnRate: 2.2,
    globalCap: 20,
    weather: 'rain',
    accident: false,
  },
  fog: {
    label: 'Fog',
    icon: '🌫️',
    description: 'Low visibility',
    spawnRate: 2.6,
    globalCap: 16,
    weather: 'fog',
    accident: false,
  },
  snow: {
    label: 'Snow',
    icon: '❄️',
    description: 'Slippery conditions',
    spawnRate: 3.0,
    globalCap: 14,
    weather: 'snow',
    accident: false,
  },
  accident: {
    label: 'Accident',
    icon: '🚨',
    description: 'Lane A (N) blocked — emergency in progress',
    spawnRate: 2.5,
    globalCap: 18,
    weather: 'clear',
    accident: true,
    accidentLane: 'NA',
  },
};